export const units = [
  {
    id: 1,
    title: "The Global Tapestry",
    period: "1200-1450",
    weight: "8-10%",
    color: "bg-purple-500",
    topics: [
      "Developments in Song China and Dar-al-Islam",
      "Kingdoms in South and Southeast Asia",
      "Developments in states in the Americas",
      "Developments in state-building in Africa",
      "Feudalism and developments in Europe and Japan",
    ],
  },
  {
    id: 2,
    title: "Networks of Exchange",
    period: "1200-1450",
    weight: "8-10%",
    color: "bg-purple-500",
    topics: [
      "Trade along networks of exchange",
      "The Silk Roads and the Mongol Empire",
      "Indian Ocean Trade Network",
      "Trans-Saharan Trade Network",
      "Cultures around the world changed with connection",
      "The spread of disease and migration of crops through networks of exchange",
    ],
  },
  {
    id: 3,
    title: "Land-Based Empires",
    period: "1450-1750",
    weight: "12-15%",
    color: "bg-green-500",
    topics: [
      "Gunpowder Empires: Ottoman, Safavid, Mughal Empires - expanded with gunpowder weapons",
      "The consolidation and legitimization of power of Gunpowder Empires",
      "Changes in religion, Protestant Reformation, syncretic beliefs",
    ],
  },
  {
    id: 4,
    title: "Maritime Empires",
    period: "1450-1750",
    weight: "12-15%",
    color: "bg-green-500",
    topics: [
      "Technological innovations allowed for maritime expansion",
      "The Columbian Exchange",
      "The effects of the Columbian Exchange, Atlantic System, Trans-Atlantic trade, Slave Trade",
      "New economic policies used by states",
    ],
  },
  {
    id: 5,
    title: "Revolutions",
    period: "1750-1900",
    weight: "12-15%",
    color: "bg-red-500",
    topics: [
      "Enlightenment ideals challenged traditional values",
      "Nationalism led to independence movements",
      "American, Latin American, French and Haitian Revolutions",
      "The Industrial Revolution, causes and changes to hierarchies",
    ],
  },
  {
    id: 6,
    title: "Consequences of Industrialization",
    period: "1750-1900",
    weight: "12-15%",
    color: "bg-red-500",
    topics: [
      "Rationales for imperialism",
      "State expansion and responses to expansion",
      "Economic development and economic imperialism",
      "Causes and effects of migration",
    ],
  },
  {
    id: 7,
    title: "Global Conflict",
    period: "1900-present",
    weight: "8-10%",
    color: "bg-yellow-500",
    topics: [
      "Shifting of power",
      "Causes and effects of World War I",
      "Great Depression and the Interwar Period",
      "Causes and effects of World War II",
      "Mass atrocities committed",
    ],
  },
  {
    id: 8,
    title: "Cold War and Decolonization",
    period: "1900-present",
    weight: "8-10%",
    color: "bg-yellow-500",
    topics: [
      "Causes and effects of the Cold War",
      "Spread and containment of communism",
      "Decolonization and state-building",
    ],
  },
  {
    id: 9,
    title: "Globalization",
    period: "1900-present",
    weight: "8-10%",
    color: "bg-yellow-500",
    topics: [
      "Advancements in technology, Green Revolution",
      "Spread of disease in the globalized world",
      "Environmental effects of globalization",
      "Reform, resistance, and cultural effects of globalization",
      "World Bank, IMF",
      "The United Nations",
    ],
  },
];
